ALTER TABLE listings DROP COLUMN IF EXISTS longitude;
ALTER TABLE listings DROP COLUMN IF EXISTS latitude;
ALTER TABLE listings DROP COLUMN IF EXISTS currency;
ALTER TABLE listings DROP COLUMN IF EXISTS price;
