ALTER TABLE listings ADD COLUMN price BIGINT NOT NULL DEFAULT 0;
ALTER TABLE listings ADD COLUMN currency VARCHAR(8) NOT NULL DEFAULT 'UAH';
ALTER TABLE listings ADD COLUMN latitude DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN longitude DOUBLE PRECISION;
